name = "extraordinary_energy_modern"
author = "Sponeru"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e728a2a0683fca1a8aa65b3190e98e93d1bc66804bc0434ab44ba624781703a5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
