
#Travel Anchors Client Configuration
[general]
	#The maximum angle you can look at the Travel Anchor to teleport.
	#Range: 1.0 ~ 180.0
	max_angle = 30.0
	#When this is set, you won't be able to use the elevation feature of travel anchors,
	#but you'll teleport to the anchor you're looking at when jumping on another travel anchor.
	#This is a client option so each player can adjust it as they prefer.
	disable_elevation = false
	#When this is set, you'll keep your velocity by default after using the short-range teleport.
	#Otherwise, your velocity will be reset by default. This behavior can be inverted by holding Ctrl.
	#This is a client option so each player can adjust it as they prefer.
	keepVelocityOnTeleport = false

