name: Build Packs (Nightly)

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: short-sha
        uses: benjlevesque/short-sha@v3.0

      - name: Install Packwiz
        uses: actionhippie/install-packwiz@v1

      - name: Build Packs
        run: |
          packwiz curseforge export -o "extraordinary_energy_modern-nightly-${{ env.SHA }}.zip"
          packwiz curseforge export -s server -o "extraordinary_energy_modern-server-nightly-${{ env.SHA }}.zip"

      - name: Unpack Client Pack
        run: | 
          mkdir -p ./build/client
          unzip "extraordinary_energy_modern-nightly-${{ env.SHA }}.zip" -d ./build/client
          rm -rf ./build/client/.github
          cp ./build/client/overrides/LICENSE ./build/client/LICENSE
          rm -rf ./build/client/overrides/LICENSE

      - name: Unpack Server Pack
        run: | 
          mkdir -p ./build/server
          unzip "extraordinary_energy_modern-server-nightly-${{ env.SHA }}.zip" -d ./build/server
          rm -rf ./build/server/.github
          cp ./build/server/overrides/LICENSE ./build/server/LICENSE
          rm -rf ./build/server/overrides/LICENSE

      - name: Upload Client build result
        uses: actions/upload-artifact@v4
        with:
          name: extraordinary_energy_modern-nightly-${{ env.SHA }}
          path: ./build/client/
          retention-days: 7

      - name: Upload Server build result
        uses: actions/upload-artifact@v4
        with:
          name: extraordinary_energy_modern-server-nightly-${{ env.SHA }}
          path: ./build/server/
          retention-days: 7